apiVersion: apps/v1
kind: Deployment
metadata:
  name: stuff-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stuff
  template:
    metadata:
      labels:
        app: stuff
    spec:
      containers:
        - name: stuff
          image: morelcorp/stuff
          # image: us.gcr.io/gitstuff-dev-301616/stuff
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: MONGO_URI
              value: 'mongodb://stuff-mongo-srv:27017/stuff'
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: gitstuff
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: stuff-srv
spec:
  selector:
    app: stuff
  ports:
    - name: stuff
      protocol: TCP
      port: 3000
      targetPort: 3000
